### ISSUE TITLE
Question: setGridSize

### ISSUE THREAD

**Issue by CollinGraf314** [tiberiuzuld/angular-gridster2#326] opened 2018-05-08 17:18 UTC
I was playing around with setGridSize, and all it really seems to do is force any gridType to behave like gridType: 'fit'.

Isn't the expected functionality of setGridSize to enlarge the grid itself, and leave the gridster-items sizes untouched?

**Comment by tiberiuzuld** [comment] 2018-05-08 19:15
Hi @CollinGraf314 ,
There was a bug and the option `setGridSize` was not working correctly.
Fixed now in v6.0.2
The option will set the gridster width and height depending on the content, usable if you want to have a page scroll and not a scroll in gridster.

Let me know if you find any more issues.

Thanks

**Closed by tiberiuzuld** 2018-05-08 19:15 UTC
Labels: bug

**Comment by ThomasPe** [comment] 2018-06-26 14:20
Maybe related to this - I've enabled setGridSize since I want to use page scroll. The grid needs to remain responsive though. When making the browser window smaller the grid resizes as expected, but when I make the window wider the applied width won't increase anymore.

Is this something you can reproduce?

**Comment by CollinGraf314** [comment] 2018-06-26 16:24
I am using setGridSize with a gridType of verticalScroll and it works fine for me. If you could make a stackblitz reproducing the issue I could take a look.

**Comment by ThomasPe** [comment] 2018-06-29 18:16
After some refactoring I can't reproduce the issue anymore ^^
Sorry for the stir up

**Comment by suraj740** [comment] 2020-06-22 16:11
Hi all, i found one issue by setting setGridSize to true, griditems doesnt resize on window resize anymore.
I am using this option with  gridType of verticalFixed.
Can anyone please help.
i have created reproducible demo for the same [demo](https://stackblitz.com/edit/angular-v7nqj4-otmnfx?file=src%2Fapp%2Fsidenav-responsive-example.ts)
