### ISSUE TITLE
Disable horizontal scroll on drag v2

### ISSUE THREAD

**Issue by nickbullock** [tiberiuzuld/angular-gridster2#440] opened 2018-11-16 09:24 UTC
Hi! Thanks for this lib, it's great.
My issue is actually this one https://github.com/tiberiuzuld/angular-gridster2/issues/244
We are using gridster with gridType=verticalScroll, fixed rows and cols width and limited maxRows, so there is really no need to scroll horizontal on drag. This behavior is strange for our users. Can you please implement flag to disable horizontal scroll?

**Comment by tiberiuzuld** [comment] 2018-11-17 10:04
Duplicate of https://github.com/tiberiuzuld/angular-gridster2/issues/402
Will track in #402

**Closed by tiberiuzuld** 2018-11-17 10:04 UTC
Labels: enhancement
