### ISSUE TITLE
display: none automatically added to a widget item

### ISSUE THREAD

**Issue by BrsJsk** [tiberiuzuld/angular-gridster2#392] opened 2018-07-18 14:24 UTC
Could there be a specific reason why 'display: none' is being added on some widget items? Could not find a reason why it was happening.
Gridster items are just being created using ngFor, some of them are displayed, and some of them are not.

Anyone knows what might be the reason for this behaviour?

**Comment by CollinGraf314** [comment] 2018-07-30 13:53
This is not a problem I've ever run into before, would you be able to create a minimum reproduction on stackblitz and post it?

**Comment by CollinGraf314** [comment] 2018-08-07 14:11
Is there any update on this? I have a strong feeling this is a bug specific to your implementation, but I just want to make sure you can't reproduce before I close the issue.

**Closed** 2018-08-13 19:08 UTC
Labels: question

**Comment by apnamulk208** [comment] 2020-01-10 11:48
facing this issue.

**Comment by Jagan-P** [comment] 2022-06-08 13:10
@CollinGraf314  facing the same issue. Will try to debug this and post a solution if I find.

**Comment by Jagan-P** [comment] 2022-06-08 14:15
> @CollinGraf314 facing the same issue. Will try to debug this and post a solution if I find.

Sorry, mine was because of a different issue in my implementation.
