### ISSUE TITLE
Dynamic Columns Support for Gridster

### ISSUE THREAD

**Issue by smoore2386** [tiberiuzuld/angular-gridster2#195] opened 2017-12-20 01:57 UTC
Would it be possible to have a dynamic columns option available for gridster.  

Something like below,  but grid would auto position widgets that exceed max columns. When screen resizes (larger) the items would move back to their original position if it does not violate maxcolumns.

Maybe add options dynamicColumns: { minWidth:colWidth} 

`
    const columns = Math.floor(screenWidth / minColWidth);

    if (columns !== this.gridster.columns) {
      this.options.maxCols = columns;
      this.options.minCols = columns;
      this.columnsChanged = true;

      if (this.options.api)
        this.options.api.optionsChanged();

      this.gridster.grid.forEach((item: GridsterItemComponent, i) => {
        let idx = findIndex(this.dashboard, ['id', item.item.id]);
        if ((item.$item.cols + item.item.position[this.screenSize].x) >= columns) {
            // this is meant to correctly auto position item. Not
            this.options.api.getNextPossiblePosition(item.$item);
            this.dashboard[idx].gridItem.position['tmpPos'] = item.$item;
});
`
Really appreciate your work
thanks

**Comment by tiberiuzuld** [comment] 2017-12-20 07:17
Hi @smoore2386 ,
Why do you need it to have a fixed maxCols ?
Not having this constrait the grid will always set itself cols to max `item.x + item.cols`.

Why do you need this use case?

Thanks

**Comment by smoore2386** [comment] 2017-12-31 13:15
Sorry maybe I phrased the question incorrectly. 

I am trying to achieve dynamic columns similar  to this implementation
https://cdn.rawgit.com/arkabide/angular-gridster/dynamic-colums/index.html#/main

Clicking the dynamic columns selection will auto position orphaned items. When the screen resized wider the items go back to their original position. This is the functionality I am looking for 

Here is how I have it (somewhat working) in my current app. This works pretty good but sometimes I run into collisions when resizing. Smaller width -> larger
The main logic is in the `computeCols Function`

```
// Options 
  options: GridsterConfig = {
    gridType: 'verticalFixed',
    compactType: 'none',
    mobileBreakpoint: 640,
    margin: 10,
    minCols: 10, // minimum amount of columns in the grid
    maxCols: 10, // maximum amount of columns in the grid
    minRows: 1, // minimum amount of rows in the grid
    maxRows: 12, // maximum amount of rows in the grid
    outerMargin: true,
    minItemCols: 1,
    minItemRows: 1,
    maxItemRows: 2,
    maxItemCols: 2,
    itemInitCallback: (i, c) => this.itemInitCallback(i, c),
    defaultItemCols: 2,
    defaultItemRows: 2,
    fixedColWidth: 180,
    fixedRowHeight: 180,
    displayGrid: 'onDrag&Resize',
    keepFixedHeightInMobile: true,
    disableWindowResize: false,
    disablePushOnResize: false,
    draggable: {
      enabled: true,
      delayStart: 200, // milliseconds to delay the start of resize, useful for touch interaction
      ignoreContent: true, // if true drag will start only from elements from `dragHandleClass`
      dragHandleClass: 'drag-handle', // drag event only from this class. If `ignoreContent` is true.
      stop: (p, q, r) => this.updatePosition(p, q, r), // callback when dragging an item stops.  Accepts Promise return to cancel/approve drag.
      start: undefined // callback when dragging an item starts.
      // Arguments: item, gridsterItem, event
    },
    resizable: {
      enabled: false,
    },
    swap: false,
    pushItems: false,
  };
```

```
constructor(){
    Observable.fromEvent(window, 'resize')
      .distinctUntilChanged()
      .subscribe((event) => {
        this.computeCols(event);
      });
}

  /** computeCols - computer col width and update options **/
  private computeCols() {
    //compute the maximum amount of columns
    const width = (window.innerWidth);
    const minColWidth = 180;
    const gridColWidth = this.gridster.curColWidth;
    const cols = this.gridster.columns;
    const columns = Math.floor(width / minColWidth);

    if (width >= 1024 && !this.mobileCheck()) {
      this.screenSize = 'desktop';
    }
    if (width < 1024 && this.mobileCheck()) {
      this.screenSize = 'tablet';
    }

    // now set the columns to what we want
    if (columns !== this.gridster.columns) {
     // set max and min to the same so columns are fixed
      this.options.maxCols = columns;
      this.options.minCols = columns;
      this.columnsChanged = true;

      if (this.options.api)
        this.options.api.optionsChanged();

      this.gridster.grid.forEach((item: GridsterItemComponent, i) => {
        let idx = findIndex(this.dashboard, ['id', item.item.id]);
        if ((item.$item.cols + item.item.position[this.screenSize].x) >= columns) {
            // this is meant to correctly auto position item. When size gets smaller
            this.options.api.getNextPossiblePosition(item.$item);
            this.dashboard[idx].gridItem.position['tmpPos'] = item.$item;
          }else{
             // Width got bigger and original position is legit delete tmpposition
            if (this.dashboard[idx].gridItem.position['tmpPos'] && // delete tmp position if real pos fits
              !((item.$item.cols + this.dashboard[idx].gridItem.position[this.screenSize].x) >= columns)) {
              delete this.dashboard[idx].gridItem.position['tmpPos']
            }

          }
      });
    }
    return this.columnsChanged;
  }

```

Again thanks. I guess my questions is could this be implemented or does this already work and I am not configuring my options correctly.

**Comment by tiberiuzuld** [comment] 2018-01-03 08:31
Ok now I understand what you want.

The problem is that if you change the item position without saving it to db then what do you do if the user resizes or drag?

If you don't need to use resize or drag then it can work but you should better use [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)

If you need drag and resize then you need to disable it when moving items to temporary positions.

Or only when you are in a small screen use [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout), you can do that by overriding the css from the gridster.mobile and using the option `mobileBreakpoint`

**Comment by klemenoslaj** [comment] 2018-01-09 20:15
This feature would be really nice to have indeed.

I think you don't need to store it to db if gridster renders items automatically due to the lack of space. But if the user now makes a change you would have to store the new grid to db, which is of course smaller/bigger than original grid(before resizing). I think that this is acceptable behavior.

However, in my opinion, how developers will cope with such issue is up to them though :)

Is there any hope to get this build in?

**Comment by tiberiuzuld** [comment] 2018-01-09 20:37
I don't think you understood what I was asking.
What I said in the post above is that what are you suggesting if the user can drag and resize after the "temp" move will create conflicts. 
I don't think this is an acceptable behavior. 
I think you should use case grid under the mobileBreakpoint.

**Closed** 2018-01-13 12:28 UTC
Labels: question

**Comment by smoore2386** [comment] 2018-04-19 13:27
Have been using this in the past couple months in production. It has been performing really well. Some tweaks here and there when it comes to colWidth. 

Sorry for not replying sooner on this.  In my app i do not store then tmpPosition even if they move the item. I have just updated to latest release. Will be creating a branch to see if I can get a demo together.

To address your concern:
tmpPos never gets stored because I just update the whole grid. The mobile checks handle the different screen sizes:
```js
{
  gridItem: {
    cols: 2,
    id: '-L6Nl9-e1CxJQzIXbl2O',
    position: {
      desktop: {
        x: 6,
        y: 0
      },
      phone: {
        x: -1,
        y: -1
      },
      tablet: {
        x: 0,
        y: 6
      },
      widescreen: {
        x: -1,
        y: -1
      }
    },
    rows: 2,
    x: 6,
    y: 0
  }
}
```
```js
  /**
   * updateGridItems - update the whole grid when we stop moving a grid item
   */
  updateGridItems() {
    const ourItems = [];
    this.gridster.grid.forEach((gridItem: DashterItem, i) => {
      const ourItem: DashterItem = { ...gridItem.item };
      if (ourItem.hasOwnProperty('configure')) delete ourItem.configure;
      if (ourItem.hasOwnProperty('pendingRemoval'))
        delete ourItem.pendingRemoval;
      ourItem.position[this.screenSize] = {
        x: gridItem.$item.x,
        y: gridItem.$item.y
      };
      ourItem.x = gridItem.$item.x;
      ourItem.y = gridItem.$item.y;
      ourItems.push(ourItem);
    });
    this.store.dispatch(new UpdateGridItems(ourItems));
  }
```
