### ISSUE TITLE
[BUG] Unable to resize in some cases

### ISSUE THREAD

**Issue by felipeinfantino** [tiberiuzuld/angular-gridster2#533] opened 2019-07-29 09:24 UTC
Relating to issue #475 , is there some solution or workaround ? Can anyone help me to understand what is happening there ?

**Comment by felipeinfantino** [comment] 2019-08-17 09:27
Should be fixed with this pr https://github.com/tiberiuzuld/angular-gridster2/pull/538

**Comment by tiberiuzuld** [comment] 2019-08-26 18:42
Closed duplicate of #475

**Closed by tiberiuzuld** 2019-08-26 18:42 UTC
Labels: duplicate
