### ISSUE TITLE
Cannot Read Property 'x' of undefined

### ISSUE THREAD

**Issue by CollinGraf314** [tiberiuzuld/angular-gridster2#517] opened 2019-06-18 14:32 UTC
If you select the text in a widget, then drag and drop the text instead of a widget, the widget your cursor was initially over will get stuck to your cursor and if you make any clicks with the widget stuck, you get the error `Cannot Read Property 'x' of undefined`.

Stackblitz (courtesy of @hannecolaers #514):  https://stackblitz.com/edit/angular-6lsknr?file=src%2Fapp%2Fapp.component.ts 

![gridster2Bug](https://user-images.githubusercontent.com/9330290/59692901-e80f4880-91b3-11e9-861a-262d96fc2c69.gif)

**Comment by tiberiuzuld** [comment] 2019-08-26 19:26
Close duplicate of #514

**Closed by tiberiuzuld** 2019-08-26 19:26 UTC

**Comment by duongth52** [comment] 2019-09-17 09:11
Hello,
I have the same issue as CollinGraf314 :
"Cannot read property 'x' of undefined in GridsterDraggable.calculateItemPosition".
I use angular-gridster2 version 3.19.0 and angular 4.x.
