### ISSUE TITLE
Automatically change height of gridster div

### ISSUE THREAD

**Issue by samarsiraj** [tiberiuzuld/angular-gridster2#67] opened 2017-06-28 13:03 UTC
Hello,

In gridster.js (implemented as a jQuery plugin) the height of the gridster div is changed automatically. In angular-gridster2, this is not done which causes the widgets to compress vertically. With `gridType: 'fit'`, the widget height remains constant, but so does the gridster div. Isn't it better to change the height of the gridster div automatically so that widgets aren't compressed vertically?

Thanks

**Comment by tiberiuzuld** [comment] 2017-06-28 13:18
Hi @samarsiraj ,
The grid will take all the space given to it. 
Yes in that way is the reverse way of how `gridster.js` is doing it.

The `gridType: 'fit'` will fit in the all available space. 

If you want not to compress vertically choose `gridType: 'scrollVertical'`.

How the `angular-gridster2` is working internally now cannot be changed to behave like `gridster.js`.
The width of a column and the height of a row is determined by the width and height of the `gridster` div and the total number of rows and columns.
You can see the code [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridster.component.ts) at line 158

**Comment by tiberiuzuld** [comment] 2017-07-01 11:26
Hi @samarsiraj ,

Closing issue since no more activity and the grid will not change the behavior.

Thanks,

**Closed by tiberiuzuld** 2017-07-01 11:26 UTC
Labels: question

**Comment by yvahava** [comment] 2018-03-20 07:45
Is there a way to change the height of the gridster div in the angularjs version of the library ?

**Comment by tiberiuzuld** [comment] 2018-03-20 10:29
Yes read here #275

**Comment by yvahava** [comment] 2018-03-20 10:38
I'm actually using angular-gridster ( not the second version )
I'm trying to implement a dashboard system and have a grid resize its
height ( which is actually contained within another grid ) such like ...

<div gridster>
  <div gridster-item>
   <div gridster-item>
         <div gridster></div>
    </div>
  </div>
</div>

so I need to be able to resize the internal gridster

**Comment by tiberiuzuld** [comment] 2018-03-20 10:48
If you are not using this library eg: `angular-gridster2` why are you asking here?
This library supports angularjs 1.x also the documentation is here: https://github.com/tiberiuzuld/angular-gridster2/tree/1.x

**Comment by yvahava** [comment] 2018-03-20 11:20
oh, thank you !!

I didn't realize it supports angularjs !!

**Comment by yvahava** [comment] 2018-03-27 07:07
I started using the gridster2 angularjs version.  I'm seeing an issue
sometimes when I define a grid inside a grid.  I will move widgets around
and at
one point the widgets will start shaking around the screen.   I see error
message ...

Uncaught TypeError: Cannot read property 'x' of undefined
    at Object.vm.calculateItemPosition (gridster.js:1913)
    at Object.vm.calculateItemPositionFromMousePosition (gridster.js:1833)
    at gridster.js:273

**Comment by tiberiuzuld** [comment] 2018-03-27 11:28
Have no clue why.
PR's are welcomed if you find what is the cause and when it happens.

**Comment by yvahava** [comment] 2018-05-29 13:43
I'm encountering this issue with gridster 2.  I have a resizable gridster
div with a widget in it.  I have functionality that disables resize and
drag on everything.  When I toggle back to enable and then attempt to
resize a widget, the gridster resizes along with it.

**Comment by nancyhan2017** [comment] 2018-10-27 21:55
I have a similar issue. If I highlight a label on any gridsterItem, then resize an item, it moves around. I cannot stop it.
