### ISSUE TITLE
angular/cli warnings cannot find source files

### ISSUE THREAD

**Issue by ianqueue** [tiberiuzuld/angular-gridster2#68] opened 2017-06-29 16:22 UTC
Another thread on this issue can be referenced here... https://github.com/angular/angular-cli/issues/2364
<img width="1820" alt="screen shot 2017-06-29 at 12 20 54 pm" src="https://user-images.githubusercontent.com/239773/27698577-86c89bc8-5cc5-11e7-8029-1fd0e7227df3.png">

using `@angular-cli/latest`.

Thanks.

**Comment by tiberiuzuld** [comment] 2017-06-29 22:02
Hi @ianqueue ,
I couldn't reproduce the issue. For me it works perfectly.

```json
{
  "name": "test-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod --base-href=./",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "4.2.4",
    "@angular/compiler": "4.2.4",
    "@angular/core": "4.2.4",
    "@angular/forms": "4.2.4",
    "@angular/http": "4.2.4",
    "@angular/platform-browser": "4.2.4",
    "@angular/platform-browser-dynamic": "4.2.4",
    "@angular/router": "4.2.4",
    "angular-gridster2": "3.1.0",
    "core-js": "2.4.1",
    "rxjs": "5.4.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "4.2.4",
    "@types/jasmine": "2.5.53",
    "@types/node": "8.0.6",
    "codelyzer": "3.1.1",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "protractor": "5.1.2",
    "ts-node": "3.1.0",
    "tslint": "5.4.3",
    "typescript": "2.3.4"
  }
}
```

**Comment by tiberiuzuld** [comment] 2017-07-01 11:28
Hi @ianqueue ,

Closing issue since I cannot reproduce it and there is no more other comments.
If you still can reproduce it reply with a package.json, node version, npm version.

Thanks,

**Closed by tiberiuzuld** 2017-07-01 11:28 UTC
Labels: question
