### ISSUE TITLE
Vertical resize wrong mouse offset when page is scrolled

### ISSUE THREAD

**Issue by FrozenGenis** [tiberiuzuld/angular-gridster2#85] opened 2017-07-19 15:06 UTC
When the page is scrolled and you initiate the vertical resize event, it calculates the offset wrongly.

(The red dot represents my mouse position)
Before click:
https://prnt.sc/fxo0a1
After click:
https://prnt.sc/fxo0o4

When the page is scrolled all the way to the top, this issue doesn't occur.

**Comment by tiberiuzuld** [comment] 2017-07-20 04:46
Hi @FrozenGenis ,
On the demo page I am not able to reproduce the issue. 
Please make sure you use the latest version.

Thanks,

**Comment by nowone12** [comment] 2017-07-21 11:59
Hi @tiberiuzuld 
I am also facing the same issue.
the demo page is no scrollbar. 

Thanks.

**Comment by tiberiuzuld** [comment] 2017-07-21 12:38
Hi @nowone12 ,

Tested again with scroll on body and could reproduce it.
Will have a fix this weekend.

Thank you,

**Comment by tiberiuzuld** [comment] 2017-07-22 11:33
Hi @nowone12 and @FrozenGenis ,

Fixed in v3.6.0.

Thanks,

**Closed by tiberiuzuld** 2017-07-22 11:33 UTC
Labels: bug

**Comment by FrozenGenis** [comment] 2017-07-24 07:29
Thanks!

**Comment by nowone12** [comment] 2017-07-24 09:36
Thanks!
